---
title: "Ciberseguridad en estudiantes de licenciatura"
subtitle: "Presentación de la información"
author: "Equipo 1: Diego Arellano, Emilio Ramírez, Fernanda Monter,   Fernando Lango"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
    prettydoc::html_pretty:
        theme: cayman
        highlight: github
        number_sections: true
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

¿Cómo se compone nuestra población?

¿Qué percepción tienen sobre la ciberseguridad?

¿Qué tan expuestos se encuentran?

¿Cuáles son sus dispositivos utilizados?

¿Cuáles son los dispositivos más utilizados?

¿Cuáles son las redes sociales utilizadas?

¿Cuáles son las redes sociales más utilizadas?

¿Cuáles son sus hábitos en compras en línea?

¿Qué importancia le dan a los términos y condiciones y cookies al navegar?

¿Han sido víctimas de amenazas y ataques digitales?

¿Conocen a alguien que haya sido víctima de un ataque digital? ¿Crees que estos ataque se pudieron haber evitado?

¿Cuáles son las medidas de seguridad más utilizadas?

¿Qué medidas de protección tiene activadas en el navegador?

¿Qué tanto les preocupa su información?

¿Qué tan fácil dan su información?



















